#!/bin/sh

if [ -f src/Makevars ]; then
  (cd src; make -f Makevars clean)
else
  (cd src; make -f Makevars.in clean)
fi

rm -rf a.out.dSYM
rm -rf autom4te.cache
rm -f config.log
rm -f config.status
rm -f src/config.hpp
rm -f src/external/config.h
rm -f src/Makevars

# from rstan.package.skeleton
R_HOME=`R --slave -e 'cat(R.home())'`
mkdir -p src/include
"${R_HOME}/bin/R" --vanilla --slave --file=tools/make_cpp.R
sed -i.bak '/current_statement_begin__ = [0-9]/d' src/include/models.hpp
cat src/*.cc > src/Modules.cpp
rm src/*.cc

